# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mr49p1lP0jq3LU9A5NC01iLXvO7ka7OR
"""

a=30
b=7

add=a+b
sub=a-b
mul=a*b
div=a/b
mod=a%b

print(add)
print(sub)
print(mul)
print(div)
print(mod)

q=int(div)

print(q)